name = "Zula"
author = "py"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "805202bff98229368ad737d6fe4eac248b93e9472889c4ccef9a1d0edcf7b2a1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
