name = "Zula"
author = "py"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83702a66bf20b5ea15b6186de25280f14d35e225775c120f3cba12f28cc57e5f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
