name = "gel2"
author = "py"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b300c15f3af24f7717053592ccaff9bc70baea4d3624c540fdb8c30988f09fd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.168"

[options]
acceptable-game-versions = ["1.21"]
