name = "gel2"
author = "py"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc0ce766d2d088b5cbc6386037d7e98d1ac66d27a9aa9a7c5730b2e316e7dfdd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.168"

[options]
acceptable-game-versions = ["1.21"]
