name = "gel2"
author = "py"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ad7eea9a2a4e24476569cbffd0a25bcc4d112ab53ceecd451ce6ae710248f01"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.168"
