name = "gel2"
author = "py"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf010df39768b4eaec5b8b47fee9eb32aaf92a4383baea8f33848fb845583f3f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.168"
